# Generated by Django 3.0.3 on 2020-02-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha Nacimiento')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Género')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='Creado por')),
                ('updated_user', models.CharField(blank=True, max_length=64, null=True, verbose_name='Actualizado por')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
