# Generated by Django 3.0.3 on 2020-02-21 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=16, unique=True, verbose_name='Cedula')),
                ('vocation', models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundaria')], max_length=2, verbose_name='Formación')),
                ('cellphone', models.PositiveSmallIntegerField(blank=True, max_length=8, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['user'],
            },
        ),
    ]
