# Generated by Django 3.0.3 on 2020-02-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=16, unique=True)),
                ('vocation', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Formacion')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Person', verbose_name='Docente')),
            ],
        ),
    ]
