# Generated by Django 3.0.3 on 2020-02-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
    ]
