# Generated by Django 3.0.3 on 2020-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vocation',
            field=models.CharField(choices=[('P', 'Primaria'), ('S', 'Secundaria')], max_length=2, verbose_name='Formacion'),
        ),
    ]
