# Generated by Django 3.0.3 on 2020-02-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200227_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_brothers_center', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], verbose_name='¿Tiene hermanos en el centro?')),
                ('how_many', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='¿Cuántos?')),
                ('religion', models.CharField(max_length=20, null=True, verbose_name='Religión')),
                ('origin_center', models.CharField(max_length=50, null=True, verbose_name='Centro de Procedencia')),
                ('year_taken_origin_center', models.CharField(choices=[('I', '1er Nivel'), ('II', '2do Nivel'), ('III', '3er Nivel'), ('1er', '1er Grado'), ('2do', '2do Grado'), ('3er', '3er Grado'), ('4to', '4to Grado'), ('5to', '5to Grado'), ('6to', '6to Grado'), ('7mo', '7mo Grado'), ('8vo', '8vo Grado'), ('9no', '9no Grado'), ('10mo', '10mo Grado'), ('11vo', '11vo Grado')], max_length=4, null=True, verbose_name='Año cursado del centro de procedencia')),
                ('diseases', models.CharField(blank=True, max_length=350, null=True, verbose_name='Enfermedades')),
                ('in_emergencies_call', models.CharField(blank=True, max_length=350, null=True, verbose_name='En caso de emergencias llamar a')),
            ],
            options={
                'verbose_name': 'Expediente Personal',
                'verbose_name_plural': 'Expedientes Personales',
            },
        ),
    ]
