# Generated by Django 3.0.3 on 2020-02-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_personalfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Genero')),
                ('status', models.SmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Reingreso'), (3, 'Inactivo')], max_length=2, verbose_name='Estado Estudiante')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Nationality', verbose_name='Nacionalidad')),
            ],
        ),
    ]
