# Generated by Django 3.0.3 on 2020-02-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Reingreso'), (3, 'Inactivo')], verbose_name='Estado Estudiante'),
        ),
    ]
