# Generated by Django 3.0.3 on 2020-02-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200227_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
