# Generated by Django 3.0.3 on 2020-02-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familiar', 'verbose_name_plural': 'Familiares'},
        ),
    ]
