# Generated by Django 3.0.3 on 2020-02-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200227_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family_members',
            field=models.ManyToManyField(to='school.Family', verbose_name='Familiares'),
        ),
    ]
