# Generated by Django 3.0.3 on 2020-03-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0017_auto_20200301_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('MAMA', 'MAMA'), ('TIO/A', 'TIO/A'), ('HERMANO/A', 'HERMANO/A'), ('PAPA', 'PAPA'), ('ABUELO/A', 'ABUELO/A')], max_length=20, verbose_name='Rol Familiar'),
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_year', models.DateField(verbose_name='Año Lectivo')),
                ('school_year', models.CharField(choices=[('I', '1er Nivel'), ('II', '2do Nivel'), ('III', '3er Nivel'), ('1er', '1er Grado'), ('2do', '2do Grado'), ('3er', '3er Grado'), ('4to', '4to Grado'), ('5to', '5to Grado'), ('6to', '6to Grado'), ('7mo', '7mo Grado'), ('8vo', '8vo Grado'), ('9no', '9no Grado'), ('10mo', '10mo Grado'), ('11vo', '11vo Grado')], max_length=4, null=True, verbose_name='Año Escolar')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Matricula')),
                ('Family', models.CharField(max_length=50, verbose_name='Familiar')),
                ('status', models.SmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Inactivo')], verbose_name='Estado')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
    ]
