# Generated by Django 3.0.3 on 2020-03-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200302_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('MAMA', 'MAMA'), ('TIO/A', 'TIO/A'), ('HERMANO/A', 'HERMANO/A'), ('PAPA', 'PAPA'), ('ABUELO/A', 'ABUELO/A')], max_length=20, verbose_name='Rol Familiar'),
        ),
    ]
