# Generated by Django 3.0.3 on 2020-03-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200302_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculation',
            name='Family',
        ),
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('HERMANO/A', 'HERMANO/A'), ('ABUELO/A', 'ABUELO/A'), ('PAPA', 'PAPA'), ('TIO/A', 'TIO/A'), ('MAMA', 'MAMA')], max_length=20, verbose_name='Rol Familiar'),
        ),
    ]
