# Generated by Django 3.0.3 on 2020-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20200302_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculation',
            name='teaching_year',
        ),
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('MAMA', 'MAMA'), ('ABUELO/A', 'ABUELO/A'), ('PAPA', 'PAPA'), ('TIO/A', 'TIO/A'), ('HERMANO/A', 'HERMANO/A')], max_length=20, verbose_name='Rol Familiar'),
        ),
    ]
