# Generated by Django 3.0.3 on 2020-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20200302_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculation',
            name='teaching_year',
            field=models.IntegerField(choices=[(2019, 2019)], default=2020, verbose_name='Año Lectivo'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('PAPA', 'PAPA'), ('ABUELO/A', 'ABUELO/A'), ('TIO/A', 'TIO/A'), ('MAMA', 'MAMA'), ('HERMANO/A', 'HERMANO/A')], max_length=20, verbose_name='Rol Familiar'),
        ),
    ]
