# Generated by Django 3.0.3 on 2020-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20200302_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Grado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.AlterField(
            model_name='family',
            name='family_role',
            field=models.CharField(choices=[('PAPA', 'PAPA'), ('MAMA', 'MAMA'), ('HERMANO/A', 'HERMANO/A'), ('TIO/A', 'TIO/A'), ('ABUELO/A', 'ABUELO/A')], max_length=20, verbose_name='Rol Familiar'),
        ),
    ]
