# Generated by Django 3.0.3 on 2020-03-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20200302_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_notes', models.BooleanField(default=False, verbose_name='¿Entrego boletin de notas?')),
                ('diploma', models.BooleanField(default=False, verbose_name='¿Entrego Diploma?')),
                ('birth_certificate', models.BooleanField(default=False, verbose_name='¿Entrego Partida de nacimiento?')),
                ('conduct_certificate', models.BooleanField(default=False, verbose_name='¿Entrego Certificado de conducta?')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Matriculation', verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Papeles para el Centro',
                'verbose_name_plural': 'Papeles para el Centro',
            },
        ),
    ]
