# Generated by Django 3.0.3 on 2020-03-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_papercenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimonthly_I', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bimensual I')),
                ('bimonthly_II', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bimensual II')),
                ('biannual_I', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestral I')),
                ('bimonthly_III', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bimensual III')),
                ('bimonthly_IV', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bimensual IV')),
                ('biannual_II', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestral II')),
                ('final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Final')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course', verbose_name='Asignatura_Id')),
                ('matriculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Matriculation', verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
