# Generated by Django 3.0.3 on 2020-03-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Grado'),
        ),
    ]
