# Generated by Django 3.0.3 on 2020-03-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20200312_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_members',
            field=models.ManyToManyField(blank=True, to='school.Family', verbose_name='Familiares'),
        ),
    ]
