# Generated by Django 3.0.3 on 2020-03-12 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_auto_20200312_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfile',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.Student', verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
