# Generated by Django 3.0.3 on 2020-03-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_personalfile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Student', verbose_name='Alumno'),
        ),
    ]
