# Generated by Django 3.0.3 on 2020-03-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20200314_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Grade', verbose_name='Año Escolar(A cursar)'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student', verbose_name='Alumno'),
        ),
    ]
