# Generated by Django 3.0.3 on 2020-03-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20200314_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculation',
            unique_together={('student', 'teaching_year')},
        ),
    ]
