# Generated by Django 3.0.3 on 2020-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_auto_20200314_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papercenter',
            old_name='matricula',
            new_name='matriculation',
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='teaching_year',
            field=models.IntegerField(choices=[], default=2020, verbose_name='Año Lectivo'),
        ),
    ]
