# Generated by Django 3.0.3 on 2020-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
    ]
