# Generated by Django 3.0.3 on 2020-03-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20200314_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course_id',
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Course', verbose_name='Asignatura'),
            preserve_default=False,
        ),
    ]
