# Generated by Django 3.0.3 on 2020-03-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_auto_20200318_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
    ]
