# Generated by Django 3.0.3 on 2020-03-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_auto_20200321_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='Seccion')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seccion',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
