# Generated by Django 2.2.10 on 2020-04-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculation',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='note',
            name='matriculation',
        ),
        migrations.RemoveField(
            model_name='personalfile',
            name='year_taken_origin_center',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
