# Generated by Django 2.2.10 on 2020-04-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20200404_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Grade', verbose_name='Grado')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Section', verbose_name='Seccion')),
            ],
            options={
                'verbose_name': 'Grado Seccion',
                'verbose_name_plural': 'Grados Secciones',
            },
        ),
        migrations.CreateModel(
            name='CourseGradeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course', verbose_name='Asignatura')),
                ('grade_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.GradeSection', verbose_name='Grado Seccion')),
            ],
            options={
                'verbose_name': 'Asignatura Grado Seccion',
                'verbose_name_plural': 'Asignaturas Grados Secciones',
            },
        ),
    ]
