# Generated by Django 2.2.10 on 2020-04-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20200404_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfile',
            name='year_taken_origin_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Grade', verbose_name='Año cursado del centro de procedencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Gender', verbose_name='Género'),
            preserve_default=False,
        ),
    ]
