# Generated by Django 2.2.10 on 2020-04-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_coursegradesection_gradesection'),
        ('school', '0041_auto_20200404_0323'),
    ]

    operations = [
    ]
