# Generated by Django 2.2.10 on 2020-04-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_merge_20200404_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculationGradeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradesection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.GradeSection', verbose_name='Grado y Sección')),
                ('matriculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Matriculation', verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Matrícula grado sección',
                'verbose_name_plural': 'Matrículas grados secciones',
            },
        ),
    ]
