# Generated by Django 2.2.10 on 2020-04-06 01:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_matriculationgradesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='matrigradesection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.MatriculationGradeSection', verbose_name='Matricula Grado Seccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
