# Generated by Django 2.2.10 on 2020-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_auto_20200406_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coursesgradesection',
            field=models.ManyToManyField(blank=True, to='school.CourseGradeSection', verbose_name='Projects'),
        ),
    ]
