# Generated by Django 2.2.10 on 2020-04-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_auto_20200407_0314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('matrigradesection', 'course')},
        ),
    ]
