# Generated by Django 2.2.10 on 2020-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_auto_20200407_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coursesgradesection',
            field=models.ManyToManyField(blank=True, to='school.CourseGradeSection', verbose_name='Asignaturas'),
        ),
    ]
