# Generated by Django 2.2.10 on 2020-04-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_auto_20200407_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculation',
            name='gradesection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.GradeSection', verbose_name='Grado y Sección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='matriculation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Matriculation', verbose_name='Matricula'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('matriculation', 'course')},
        ),
        migrations.RemoveField(
            model_name='note',
            name='matrigradesection',
        ),
    ]
