# Generated by Django 2.2.10 on 2020-04-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_auto_20200409_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculationgradesection',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='matriculationgradesection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matriculationgradesection',
            name='gradesection',
        ),
        migrations.RemoveField(
            model_name='matriculationgradesection',
            name='matriculation',
        ),
    ]
