# Generated by Django 2.2.10 on 2020-04-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_auto_20200409_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatriculationGradeSection',
        ),
    ]
