# Generated by Django 2.2.10 on 2020-04-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_delete_matriculationgradesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculation',
            old_name='gradesection',
            new_name='grade_section',
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, verbose_name='Estado'),
        ),
    ]
