# Generated by Django 2.2.10 on 2020-04-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_auto_20200409_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Finalizo Satisfactoriamente'), (3, 'Reprobado')], default=1, verbose_name='Estado'),
        ),
    ]
