# Generated by Django 2.2.10 on 2020-04-09 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_auto_20200409_2232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradesection',
            unique_together={('grade', 'section')},
        ),
    ]
