# Generated by Django 2.2.10 on 2020-04-15 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('school', '0058_auto_20200409_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papercenter',
            name='matriculation',
        ),
        migrations.AddField(
            model_name='papercenter',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Student',
                                    verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
