# Generated by Django 2.2.10 on 2020-04-15 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_auto_20200415_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercenter',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Student', verbose_name='Estudiante'),
        ),
    ]
