# Generated by Django 2.2.10 on 2020-04-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_auto_20200415_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalfile',
            name='origin_center',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro de Procedencia'),
        ),
        migrations.AlterField(
            model_name='personalfile',
            name='religion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Religión'),
        ),
    ]
