# Generated by Django 2.2.10 on 2020-04-16 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_auto_20200415_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11111111), django.core.validators.MaxValueValidator(99999999)], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vocation',
            field=models.CharField(choices=[('PE', 'Pre-Escolar'), ('P', 'Primaria'), ('S', 'Secundaria')], max_length=2, verbose_name='Formación'),
        ),
    ]
