# Generated by Django 2.2.10 on 2020-04-16 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_auto_20200416_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11111111, 'El celular digitado debe tener 8 digitos'), django.core.validators.MaxValueValidator(99999999, 'El celular digitado debe tener 8 digitos')], verbose_name='Celular'),
        ),
    ]
