# Generated by Django 2.2.10 on 2020-04-17 01:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_auto_20200416_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='cellphone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11111111, 'El Teléfono debene tener 8 digitos'), django.core.validators.MaxValueValidator(99999999, 'El Teléfono debene tener 8 digitos')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11111111, 'El Celular debene tener 8 digitos'), django.core.validators.MaxValueValidator(99999999, 'El Celular debene tener 8 digitos')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='papercenter',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.Student', verbose_name='Estudiante'),
        ),
    ]
