# Generated by Django 2.2.10 on 2020-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_auto_20200417_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code_mined',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codigo MINED'),
        ),
    ]
