# Generated by Django 2.2.10 on 2020-05-01 22:02

from django.db import migrations, models
import school.commons


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0068_auto_20200427_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='teaching_year',
            field=models.IntegerField(default=school.commons.get_current_year, verbose_name='Año Lectivo'),
        ),
        migrations.AlterField(
            model_name='usercoursesbyyear',
            name='year',
            field=models.IntegerField(default=school.commons.get_current_year, verbose_name='Año Lectivo'),
        ),
    ]
