# Generated by Django 2.2.10 on 2020-05-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0069_auto_20200501_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradesection',
            options={},
        ),
        migrations.AddField(
            model_name='gradesection',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='gradesection',
            unique_together=set(),
        ),
    ]
