# Generated by Django 2.2.10 on 2020-05-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0070_auto_20200509_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradesection',
            options={'verbose_name': 'Grado Seccion', 'verbose_name_plural': 'Grados Secciones'},
        ),
        migrations.AlterUniqueTogether(
            name='gradesection',
            unique_together={('grade', 'section')},
        ),
    ]
