# Generated by Django 2.2.13 on 2020-06-28 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_auto_20200513_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
    ]
