# Generated by Django 2.2.13 on 2020-06-28 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0072_auto_20200628_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='note',
            name='biannual_II_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Semestral II'),
        ),
        migrations.AddField(
            model_name='note',
            name='biannual_I_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Semestral I'),
        ),
        migrations.AddField(
            model_name='note',
            name='bimonthly_III_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Bimensual III'),
        ),
        migrations.AddField(
            model_name='note',
            name='bimonthly_II_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Bimensual II'),
        ),
        migrations.AddField(
            model_name='note',
            name='bimonthly_IV_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Bimensual IV'),
        ),
        migrations.AddField(
            model_name='note',
            name='bimonthly_I_date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación del Bimensual I'),
        ),
        migrations.AddField(
            model_name='note',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
