# Generated by Django 2.2.13 on 2020-08-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0074_auto_20200705_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Reingreso'), (3, 'Inactivo')], default=1, verbose_name='Estado Estudiante'),
        ),
    ]
