# Generated by Django 2.2.13 on 2020-09-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0075_auto_20200809_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursegradesection',
            options={'verbose_name': 'Asignatura Por Aula', 'verbose_name_plural': 'Asignaturas Por Aulas'},
        ),
        migrations.AlterModelOptions(
            name='gradesection',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
    ]
