# Generated by Django 2.2.13 on 2020-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0078_family_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
