# Generated by Django 2.2.13 on 2020-09-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0076_auto_20200911_0024'),
        ('school', '0079_family_email'),
    ]

    operations = [
    ]
