# Generated by Django 2.2.13 on 2020-11-17 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0081_auto_20201117_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(11111111, 'El Teléfono debe tener 8 digitos'), django.core.validators.MaxValueValidator(99999999, 'El Teléfono debe tener 8 digitos')], verbose_name='Teléfono'),
        ),
    ]
